apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prometheus
  annotations:
    github.com/project-slug: varuntalus/prometheus
    backstage.io/techdocs-ref: value
    argocd/app-name: prometheus
spec:
  type: other
  lifecycle: unknown
  owner: guests
